---
- name: Clean up temporary rclone files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/{{ rclone_zip_file }}"
    - "/tmp/rclone-v{{ rclone_version }}-linux-amd64"
    - "/tmp/rclone-SHA256SUMS-{{ rclone_version }}"

- name: Restart mount units
  ansible.builtin.systemd:
    name: "mnt-eumetsatdata-{{ item.dest }}.mount"
    state: restarted
    daemon_reload: false # Daemon is reloaded in tasks/main.yml at the point that is needed.
  loop: "{{ buckets }}"
  when: mount_units_templated.changed | default(false)
  loop_control:
    label: "{{ item.dest }}"
